# handlers file
---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart percona-server
  ansible.builtin.service:
    name: mysql
    state: restarted
  when: service_default_state | default('started') == 'started'
